/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/aKfWyusPGx8
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Eczar } from 'next/font/google'
import { Yeseva_One } from 'next/font/google'

eczar({
  subsets: ['latin'],
  display: 'swap',
})

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function Blog() {
  return (<>
    <div className="px-4 py-6 md:px-6 md:py-12 lg:py-16">
      <article className="prose prose-gray mx-auto max-w-6xl dark:prose-invert">
        <div className="grid gap-4 lg:grid-cols-[500px_1fr]">
          <div className="space-y-2 not-prose">
            <h1
              className="text-4xl font-extrabold tracking-tight lg:text-5xl lg:leading-[3.5rem]">
              Elevate Your Events: Planning Tips from the Experts
            </h1>
            <p className="text-gray-500 dark:text-gray-400">By Jane Doe, Published on May 15, 2024</p>
          </div>
          <div className="[&>p:first-child]:mt-0">
            <p>
              Transforming your events into stylish and memorable experiences doesn't have to be a daunting task. In
              this blog post, we'll share expert tips and tricks to help you elevate your event planning and create an
              atmosphere that reflects your unique style.
            </p>
            <p>
              Whether you're organizing a corporate gala, a wedding, or a community festival, our team of event
              professionals has curated a collection of must-have products and practical advice to guide you every
              step of the way.
            </p>
          </div>
        </div>
        <img
          alt="Cover image"
          className="aspect-video overflow-hidden rounded-lg object-cover"
          height="340"
          src="/placeholder.svg"
          width="1250" />
        <div className="mt-8">
          <h2 className="text-2xl font-bold">Introducing Our Signature Event Collection</h2>
          <p>
            At Event Oasis, we pride ourselves on offering a carefully curated selection of high-quality event decor
            products that are designed to elevate any occasion. From statement lighting fixtures to elegant tableware,
            our signature collection features the latest trends and timeless classics to suit a variety of styles and
            budgets.
          </p>
          <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
            <img
              alt="Product 1"
              className="aspect-[4/3] overflow-hidden rounded-lg object-cover"
              height="300"
              src="/placeholder.svg"
              width="400" />
            <img
              alt="Product 2"
              className="aspect-[4/3] overflow-hidden rounded-lg object-cover"
              height="300"
              src="/placeholder.svg"
              width="400" />
            <img
              alt="Product 3"
              className="aspect-[4/3] overflow-hidden rounded-lg object-cover"
              height="300"
              src="/placeholder.svg"
              width="400" />
          </div>
        </div>
        <div className="mt-8">
          <h2 className="text-2xl font-bold">Event Planning Tips from the Experts</h2>
          <p>
            Elevating your event planning doesn't have to be a daunting task. Our team of event experts has compiled a
            list of practical tips to help you transform your events and create a cohesive, visually appealing
            experience.
          </p>
          <ul className="space-y-4">
            <li>
              <h3 className="text-lg font-bold">Embrace Unique Decor</h3>
              <p>
                Incorporate different textures, patterns, and materials to add depth and visual interest to your
                event. Mix and match centerpieces, linens, and accents to create a memorable and immersive atmosphere.
              </p>
            </li>
            <li>
              <h3 className="text-lg font-bold">Experiment with Lighting</h3>
              <p>
                Lighting can make a significant impact on the ambiance of an event. Combine a mix of overhead, task,
                and accent lighting to create a warm and welcoming environment that sets the right mood for your
                guests.
              </p>
            </li>
            <li>
              <h3 className="text-lg font-bold">Personalize with Branding</h3>
              <p>
                Add personal touches to your event with custom branding and signage. These elements can help to make
                your event feel truly unique and reflective of your style and vision.
              </p>
            </li>
          </ul>
        </div>
      </article>
    </div>
    <aside
      className="px-4 py-6 md:px-6 md:py-12 lg:py-16 bg-gray-100 dark:bg-gray-800">
      <div className="prose prose-gray mx-auto max-w-6xl dark:prose-invert">
        <h2 className="text-2xl font-bold">Related Blog Posts</h2>
        <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
          <Link className="group block" href="#">
            <img
              alt="Related Post 1"
              className="aspect-[3/2] overflow-hidden rounded-lg object-cover"
              height="200"
              src="/placeholder.svg"
              width="300" />
            <h3 className="mt-4 text-lg font-bold group-hover:underline">
              5 Unforgettable Event Decor Ideas to Wow Your Guests
            </h3>
            <p className="mt-2 text-gray-500 dark:text-gray-400">
              Discover the must-have event decor items that will leave a lasting impression.
            </p>
          </Link>
          <Link className="group block" href="#">
            <img
              alt="Related Post 2"
              className="aspect-[3/2] overflow-hidden rounded-lg object-cover"
              height="200"
              src="/placeholder.svg"
              width="300" />
            <h3 className="mt-4 text-lg font-bold group-hover:underline">
              Maximizing Event Spaces: Clever Decor Ideas
            </h3>
            <p className="mt-2 text-gray-500 dark:text-gray-400">
              Transform your event spaces with these space-saving decor tips.
            </p>
          </Link>
          <Link className="group block" href="#">
            <img
              alt="Related Post 3"
              className="aspect-[3/2] overflow-hidden rounded-lg object-cover"
              height="200"
              src="/placeholder.svg"
              width="300" />
            <h3 className="mt-4 text-lg font-bold group-hover:underline">
              Color Trends: Embracing the Latest Hues for Your Events
            </h3>
            <p className="mt-2 text-gray-500 dark:text-gray-400">
              Discover the hottest color palettes to transform your event spaces.
            </p>
          </Link>
        </div>
      </div>
    </aside>
  </>);
}
