/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/4l6lqiEX3RJ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function Footer() {
  return (
    (<footer id="contact" className="bg-gray-100 py-12 dark:bg-gray-500">
      <div className="container mx-auto max-w-7xl px-4 md:px-6">
        <div className="grid grid-cols-1 gap-8 sm:grid-cols-2 md:grid-cols-4">
          <div className="space-y-4">
            <div className="flex items-center">
              <MountainIcon className="h-8 w-8 text-gray-900 dark:text-gray-50" />
              <span className="ml-2 text-lg font-semibold text-gray-900 dark:text-gray-50">Acme Inc</span>
            </div>
            <p className="text-gray-500 dark:text-gray-400">Crafting innovative solutions for the modern web.</p>
          </div>
          <div className="space-y-2">
            <h4 className="text-lg font-semibold text-gray-900 dark:text-gray-50">Product</h4>
            <nav className="space-y-1">
              <Link
                className="block text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                href="#">
                Features
              </Link>
              <Link
                className="block text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                href="#">
                  
                Pricing
              </Link>
              <Link
                className="block text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                href="#">
                Integrations
              </Link>
            </nav>
          </div>
          <div className="space-y-2">
            <h4 className="text-lg font-semibold text-gray-900 dark:text-gray-50">Company</h4>
            <nav className="space-y-1">
              <Link
                className="block text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                href="#">
                About
              </Link>
              <Link
                className="block text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                href="#">
                Blog
              </Link>
              <Link
                className="block text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                href="#">
                Careers
              </Link>
            </nav>
          </div>
          <div className="space-y-2">
            <h4 className="text-lg font-semibold text-gray-900 dark:text-gray-50">Social</h4>
            <nav className="space-y-1">
              <Link
                className="block text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                href="#">
                Facebook
              </Link>
              <Link
                className="block text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                href="#">
                Instgram
              </Link>
              <Link
                className="block text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                href="#">
                Twitter
              </Link>
            </nav>
          </div>
        </div>
        <div
          className="mt-12 border-t border-gray-200 pt-8 text-center text-sm text-gray-500 dark:border-gray-700 dark:text-gray-400">
          © 2024 shinzXdev. All rights reserved. 
        </div>
      </div>
    </footer>)
  );
}

function MountainIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>)
  );
}
