/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/aI2yf3e2ayJ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
// import Image from 'next/image'
// import run from "../component/bgimg";
import './hero.css'
export function Hero() {
  return (
    (<section
      className="w-full py-12 md:py-24 lg:py-32 xl:py-48  text-white relative">
      <div
        className="absolute inset-0 bg-[url(/placeholder.svg)] bg-cover bg-center opacity-20" />
      <div className="container px-4 md:px-6 relative z-10">
        <div className="flex flex-col items-center text-center space-y-6">
          <div className="space-y-4 you">
            {/* <Image src={run} alt="" srcset="" /> */}
            <h1
              className="text-4xl font-bold tracking-tight sm:text-5xl md:text-6xl lg:text-7xl">
              Welcome to Our App
            </h1>
            <p className="max-w-xl text-lg md:text-xl">
              Discover the power of our innovative app and transform the way you work.
            </p>
          </div>
          <Link
            className="inline-flex items-center justify-center rounded-md bg-white px-6 py-3 text-lg font-medium text-[#6366F1] shadow-lg transition-colors hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-[#6366F1]"
            href="#">
            Get Started
          </Link>
        </div>
      </div>
      <div
        className="absolute inset-0 bg-[url(/placeholder.svg)] bg-cover bg-center opacity-20" />
    </section>)
  );
}
// bg-gradient-to-r from-[#6366F1] to-[#9333EA]